### ISSUE TITLE
UniqueEntity and Symfony 3 components?

### ISSUE THREAD

**Issue by amustill** [saxulum/saxulum-doctrine-orm-manager-registry-provider#8]
I have two projects - an old project running Silex 1 and Symfony 2 components, and another running Silex 2 and Symfony 3 components.

Everything runs okay with the exception of the `UniqueEntity` constraint. It simply never gets initialised and therefore never gets called for validation, causing a `UniqueConstraintViolationException` and `PDOException` due to a duplicate entry for a key.

Is this a known issue? Has the library been tested with the Symfony 3 `Validator` component?

I will update this issue with specific findings tomorrow, February 16th, but just wanted to get any feedback ASAP.

**Comment by amustill** [comment]
As it turns out, this was due to conflicted configuration.

For the record - v3.1.0 plays nicely with Symfony 3 components.

Let's all move on...

**Comment by dominikzogg** [comment]
@amustill thank you for your own response
